curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/iflyelf/gwf/direct.txt'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/iflyelf/gwf/proxy.txt'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/iflyelf/gwf/ip/ChinaIp.txt'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/iflyelf/gwf/ip/ChinaIpv4.txt'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/iflyelf/gwf/ip/ChinaIpv6.txt'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/iflyelf/gwf/smartdns/smartdns_gfw_domain.conf'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/iflyelf/gwf/smartdns/smartdns_xiaonuo_domain.conf'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/iflyelf/gwf/smartdns/smartdns_gfw_domain_list.conf'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/iflyelf/gwf/smartdns/smartdns_xiaonuo_domain_list.conf'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/iflyelf/gwf/country.mmdb'

